# --- NAVIGATION & PLAYBACK ---
k            cycle pause; script-binding uosc/flash-pause-indicator
j            seek -10; script-binding uosc/flash-timeline
l            seek 10; script-binding uosc/flash-timeline
TAB          seek 85; script-binding uosc/flash-timeline
[            add speed -0.25; script-binding uosc/flash-speed
]            add speed 0.25; script-binding uosc/flash-speed

# --- CHAPTERS & PLAYLIST ---
ENTER        add chapter 1; script-binding uosc/flash-timeline
p            script-binding uosc/prev
n            script-binding uosc/next

# --- TRACKS & SCREENSHOTS ---
a            cycle audio
s            cycle sub
ctrl+s       async screenshot
