space           cycle pause
k               cycle pause

left            seek -5
j               seek -10
right           seek 5
l               seek 10
tab             seek 85; script-binding uosc/flash-timeline

[               no-osd add speed -0.25; script-binding uosc/flash-speed
]               no-osd add speed 0.25; script-binding uosc/flash-speed
bs              no-osd set speed 1; script-binding uosc/flash-speed

m               no-osd cycle mute; script-binding uosc/flash-volume
up              no-osd add volume 10; script-binding uosc/flash-volume
down            no-osd add volume -10; script-binding uosc/flash-volume

'               no-osd add chapter -1; script-binding uosc/flash-top-bar
enter           no-osd add chapter 1; script-binding uosc/flash-top-bar
c               script-binding uosc/chapters

<               script-binding uosc/prev
>               script-binding uosc/next
p               script-binding uosc/items

s               script-binding uosc/subtitles
a               script-binding uosc/audio
alt+o           script-binding uosc/open-config-directory
mbtn_right      script-binding uosc/menu

ctrl+s          async screenshot
q               quit

!               ignore
@               ignore
9               ignore
0               ignore
