# --- VIDEO & DISPLAY ---
hwdec=auto
fs
autofit=80%x80%

# --- ON-SCREEN DISPLAY ---
osd-bar=no
border=no
osd-font="Cascadia Mono"
video-sync=display-resample

# --- AUDIO & SUBTITLES ---
alang=jpn,jp
slang=enm,eng

sub-font="Gandhi Sans"
sub-bold=yes
sub-font-size=48
sub-margin-y=47
sub-outline-size=2.4
sub-shadow-offset=0.8

# --- SCREENSHOTS ---
screenshot-format=webp
screenshot-webp-compression=6
screenshot-webp-quality=95
screenshot-template="%F [%wH.%wM.%wS]"
screenshot-dir="D:\Images\Screenshots\mpv"

# --- CACHE & BEHAVIOR ---
cache=no
save-position-on-quit
autocreate-playlist=same
directory-mode=ignore
