# --- VIDEO & DISPLAY ---
vo=gpu-next
hwdec=auto-safe
video-sync=display-resample
fs=yes
autofit=80%x80%
border=no

# --- ON-SCREEN DISPLAY ---
osd-bar=no
osd-font="Cascadia Mono"

# --- AUDIO & SUBTITLES ---
alang=jpn,jp
slang=en,eng
sub-auto=fuzzy

sub-font="Gandhi Sans"
sub-bold=yes
sub-font-size=48
sub-margin-y=47
sub-outline-size=2.4
sub-shadow-offset=0.8

# --- SCREENSHOTS ---
screenshot-format=webp
screenshot-webp-compression=6
screenshot-webp-quality=95
screenshot-template="%F [%wH.%wM.%wS]"
screenshot-dir=" "

# --- CACHE & BEHAVIOR ---
cache=yes
demuxer-max-bytes=200MiB
demuxer-max-back-bytes=100MiB
save-position-on-quit
keep-open=yes
autocreate-playlist=same
directory-mode=ignore
